OpenVocabulary/trunk/core/src/com/kh/ov/model/Context.java
/**
Copyright (c) 2011, KnowledgeHives sp. z o.o

This file is part of OpenVocabulary.

OpenVocabulary has been invented by Sebastian Ryszard Kruk (based on previous work on JOnto project) 

OpenVocabulary is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenVocabulary is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with OpenVocabulary.  If not, see <http://www.gnu.org/licenses/>.

IMPORTANT:
1) In addition to the terms and conditions defined in the GNU Affero 
General Public License you agree to use this software to provide access 
to vocabularies, i.e., thesauri, taxonomies, and such, ONLY through 
a generally available end-point.
2) You will also notify the copyright owners, i.e., Knowledge Hives 
sp. z o.o., via email at info@knowledgehives.com, about the address 
of end-point you have setup using this software.
3) Finally, you need to ensure that the vocabularies managed using this 
software are correctly indexed by the Sindice semantic index service; 
we suggest using semantic sitemap protocol in oder to do so.

See http://opensource.knowledgehives.com/wiki/OpenVocabulary 
for more information
 */
package com.kh.ov.model;

import java.io.IOException;
import java.util.Collection;
import java.util.SortedSet;

import org.apache.lucene.index.CorruptIndexException;
import org.apache.lucene.store.LockObtainFailedException;
import org.ontoware.rdf2go.model.node.URI;

import com.kh.ov.persistance.Storage;

/**
 * @author sebastiankruk
 * This inteface defines operations possible on the definition of KOS context 
 */
public interface Context {

	/**
	 * @return label of the context
	 */
	public String getLabel();
	/**
	 * @return description of the context
	 */
	public String getDescription();
	/**
	 * @return Complete URI of the context
	 */
	public URI getNamespaceURI();
	/**
	 * @return Abbreviated name of the context
	 */
	public String getNamespaceAbbr();
	/**
	 * @return default locale of the context
	 */
	public String getLocale();
	/**
	 * @return RDF storage wrapper reference
	 */
	public Storage getStorage();
	/**
	 * @return URI of the context as {@link URI}
	 */
	public URI getURI();
	/**
	 * @return type of this context
	 */
	public ContextTypes getType();
	/**
	 * @param props list of additional properties in the context
	 */
	public void addAdditionalProperties(String...props);
	/**
	 * @param entry collection of root elements (taxonomy only)
	 */
	public void addRoot(Entry entry);
	/**
	 * @param props list of additional hierarchy creation properties
	 */
	public void addTreeProperties(String...props);
	/**
	 * @return list of additional properties in the context
	 */
	public String[]  getAdditionalProperties();
	/**
	 * @return collection of root elements (taxonomy only)
	 */
	public SortedSet<Entry> getRoots();
	/**
	 * @return list of additional hierarchy creation properties
	 */
	public String[] getTreeProperties();	
	
	public String getUrlPattern() ;
	public void setUrlPattern(String urlPattern) ;
	
	
	/**
	 * This method should be called to initiate reindexing of complete content of the KOS context
	 * @param cleanIndex <code>true</code> if this is the first time you reindex this context
	 */
	public void reindex(boolean cleanIndex) throws CorruptIndexException, LockObtainFailedException, IOException;
	
	
	/**
	 * Finds concepts by label_ values using full text index
	 * @param _label
	 * @return
	 */
	public Collection<Entry> listMatchingByLabel(String _label);
	/**
	 * Added for filtering function
	 */
	public Collection<Entry> listMatchingByLabelAndContext(String _label);
	
}

OpenVocabulary/trunk/core/src/com/kh/ov/model/TaxonomyEntry.java
/**
Copyright (c) 2011, KnowledgeHives sp. z o.o

This file is part of OpenVocabulary.

OpenVocabulary has been invented by Sebastian Ryszard Kruk (based on previous work on JOnto project) 

OpenVocabulary is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenVocabulary is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with OpenVocabulary.  If not, see <http://www.gnu.org/licenses/>.

IMPORTANT:
1) In addition to the terms and conditions defined in the GNU Affero 
General Public License you agree to use this software to provide access 
to vocabularies, i.e., thesauri, taxonomies, and such, ONLY through 
a generally available end-point.
2) You will also notify the copyright owners, i.e., Knowledge Hives 
sp. z o.o., via email at info@knowledgehives.com, about the address 
of end-point you have setup using this software.
3) Finally, you need to ensure that the vocabularies managed using this 
software are correctly indexed by the Sindice semantic index service; 
we suggest using semantic sitemap protocol in oder to do so.

See http://opensource.knowledgehives.com/wiki/OpenVocabulary 
for more information
 */
package com.kh.ov.model;

import java.util.Collection;
import java.util.List;



/**
 * This interface defines basic concepts that will allow to access different taxonomies in nomalzed way.
 * 
 * 
 * @author skruk
 * @created 17/08/2006
 */
public interface TaxonomyEntry extends Entry {

	/**
	 * Returns entry in the taxonomy that is parent in the tree to this one
	 * 
	 * @return Parent taxonomy entry
	 */
	public Entry getParent();
	
	
	/**
	 * Returns array of entries that are children of this one in the tree
	 * 
	 * @return Array of children entries
	 */
	public List<TaxonomyEntry> getSubEntries();
	
	
	
	/**
	 * Returns path from Root to this entry
	 * 
	 * @return path from Root to this entry as a array of TaxonomyEntry objects
	 */
	public List<TaxonomyEntry> getPathFromRoot();
	
	
	
	/**
	 * Return all entries below this entry
	 * 
	 * @return all entries below this entry as a collection of Taxonomy objects
	 */
	public Collection<TaxonomyEntry> getDescendents();
	
	
	/**
	 * Adds new descendant element to the list
	 * 
	 * @param _desc new descendand element
	 */
	public void addSubEntry(TaxonomyEntry _desc);
	
	
	/**
	 * Adds a list of new descendat elements to the list
	 * 
	 * @param _desc a list of new descendat elements
	 */
	public void setSubEntries(List<? extends TaxonomyEntry> _desc);
	
	
	/**
	 * Sets parent element
	 * 
	 * @param _parent parent element
	 */
	public void setParent(TaxonomyEntry _parent);
	
	
	/**
	 * Lists resources by given additional property (URI)
	 * 
	 * @param _additionalProperty additional property in this taxonomy context
	 * @return collection of resources linked from this one by given additional property
	 * @throws UnsupportedAdditionalPropertyException If given property is not registered in given taxonomy context
	 */
	public Collection<? extends TaxonomyEntry> getBy(String[] _additionalProperty)  throws UnsupportedAdditionalPropertyException;
	
	
	/* (non-Javadoc)
	 * @see java.lang.Comparable#compareTo(T)
	 */
	public int compareTo(TaxonomyEntry o);
	
	public boolean isMatch();

	public void setMatch(boolean match);
}

OpenVocabulary/trunk/core/src/com/kh/ov/model/ThesaurusEntry.java
/**
Copyright (c) 2011, KnowledgeHives sp. z o.o

This file is part of OpenVocabulary.

OpenVocabulary has been invented by Sebastian Ryszard Kruk (based on previous work on JOnto project) 

OpenVocabulary is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenVocabulary is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with OpenVocabulary.  If not, see <http://www.gnu.org/licenses/>.

IMPORTANT:
1) In addition to the terms and conditions defined in the GNU Affero 
General Public License you agree to use this software to provide access 
to vocabularies, i.e., thesauri, taxonomies, and such, ONLY through 
a generally available end-point.
2) You will also notify the copyright owners, i.e., Knowledge Hives 
sp. z o.o., via email at info@knowledgehives.com, about the address 
of end-point you have setup using this software.
3) Finally, you need to ensure that the vocabularies managed using this 
software are correctly indexed by the Sindice semantic index service; 
we suggest using semantic sitemap protocol in oder to do so.

See http://opensource.knowledgehives.com/wiki/OpenVocabulary 
for more information
 */
package com.kh.ov.model;

import java.util.Collection;


/**
 * @author sebastiankruk
 * This interface extends the definition of an abstract KOS entry to support Thesaurus entries
 */
public interface ThesaurusEntry extends Entry {

	/**
	 * Lists all concepts with more precise meaning.
	 * They can be retrieved through <code>skos:narrower</code> or inverse of <code>wns:hyponymOf</code>
	 * @return
	 */
	public Collection<ThesaurusEntry> getHyponyms();
	
	/**
	 * Lists all concepts with more general meaning.
	 * They can be retrieved through <code>skos:broader</code> or <code>wns:hyponymOf</code>
	 * @return
	 */
	public Collection<ThesaurusEntry> getHypernyms();
	
	/**
	 * Lists all concepts with opposite meaning.
	 * They can be retrieved through <code>wns:antonymOf</code>
	 * @return
	 */
	public Collection<ThesaurusEntry> getAntonyms();
	
	/**
	 * Lists all concepts with similar meaning.
	 * They can be retrieved through <code>skos:related</code> or by similarities on inverse property <code>wns:containsWordSense</code>
	 * @return
	 */
	public Collection<ThesaurusEntry> getSynonyms();
	
}

OpenVocabulary/trunk/core/web/kosselector.jsp
<?xml version="1.0" encoding="UTF-8" ?>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<%@ taglib prefix="ov" tagdir="/WEB-INF/tags"%>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Testing KOS Selector (OV Terms Filter)</title>
    <script src="/js/protoculous-effects-shrinkvars.js" type="text/javascript" charset="utf-8"></script>
    <script src="/js/tooltips.js" type="text/javascript" charset="utf-8"></script>
    <script src="/js/textboxlist.js" type="text/javascript" charset="utf-8"></script>
    <script src="/js/entryselector.js" type="text/javascript" charset="utf-8"></script>
    <script src="/js/kosselector.js" type="text/javascript" charset="utf-8"></script>
    
 	<link rel="stylesheet" href="/css/tooltip.css" type="text/css" charset="utf-8" />
 	<link rel="stylesheet" href="/css/kosselector.css" type="text/css" charset="utf-8" />
</head>
<body>
	<ov:kosselector id="ovtermsfilter" label="Simple input" hint="Start typing to choose a term" 
					preloaduris="http://www.openvocabulary.info/taxonomies/loc/Technology/Home_economics/The_house;http://www.openvocabulary.info/thesauri/ot/pl/instances/synset-dupa_wollowa-1;http://www.w3.org/2006/03/wn/wn20/instances/synset-house-noun-3"/>
	<a href="javascript:KOSSelector.instances.get('ovtermsfilter').saveNewConcepts();">Save</a>
</body>
</html>

OpenVocabulary/trunk/core/web/ovterm.jsp
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<%@ page language="java" contentType="text/html; charset=UTF-8"  pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="ov" uri="http://www.openvocabulary.info/jsp/ov" %>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="robots" content="all" />
		<meta name="generator" content="RapidWeaver" />
		
		<title>Browse - ${ term.label }</title>
		<link rel="stylesheet" type="text/css" media="screen" href="/rw_common/themes/clean/styles.css"  />
		<link rel="stylesheet" type="text/css" media="print" href="/rw_common/themes/clean/print.css"  />
		<link rel="stylesheet" type="text/css" media="handheld" href="/rw_common/themes/clean/handheld.css"  />
		<link rel="stylesheet" type="text/css" media="screen" href="/rw_common/themes/clean/css/styles/red.css" />
		<link rel="stylesheet" type="text/css" media="screen" href="/rw_common/themes/clean/css/sidebar/sidebar_right.css" />
		
    	<link rel="alternate" type="application/rdf+xml" title="RDF Version" href="${ term.URI }?rdf=true" />		
		
		
		<script type="text/javascript" src="/rw_common/themes/clean/javascript.js"></script>
		
		<style>
			label { font-weight: bold; };
		</style>
		
		
	</head>
<body>
<div id="container"><!-- Start container -->
	<div class="top">&nbsp;</div>
	
	<div id="pageHeader"><!-- Start page header -->
		<h1>OpenVocabulary</h1>
		<h2>Linking Public Vocabularies</h2>
	</div><!-- End page header -->

	<div id="navcontainer"><!-- Start Navigation -->
		<ul><li><a href="/" rel="self">Welcome</a></li><li><a href="/vocabularies/" rel="self">Vocabularies</a></li><li><a href="#" rel="self" id="current">Browse</a></li><li><a href="/vocabularies/search.html" rel="self">Search</a></li><li><a href="/sources/" rel="self">Sources</a></li></ul>
	</div><!-- End navigation -->
	
	<div id="contentContainer"><!-- Start main content wrapper -->
		<div id="content"><!-- Start content -->
		
			<c:choose>
				<c:when test="${ not empty term }">
					<h1>${ term.label }</h1>
					
					<c:if test="${ not empty term.description }">
					<blockquote>${ term.description }</blockquote>
					</c:if>
					
					<c:set var="iswn" value="${ term.context.label eq 'WordNet'}"/>
					
					<h2>URIs:</h2><%-- TODO-i18n --%>
					<ul>
						<li><a href="${ term.URI }">${ term.URI }</a></li>
						<c:if test="${ not iswn }">
							<li><a href="${ term.URI }?json=true">JSON</a></li>
							<li><a href="${ term.URI }?rdf=true">RDF/XML</a></li>
						</c:if>
					</ul>
					
					<h2>Context:</h2> <%-- TODO-i18n --%>
					<ul>
						<li><label for="contextlabel">label: </label><span id="contextlabel">${ term.context.label }</span></li> <%-- TODO-i18n --%>
						<c:if test="${ not empty term.context.description }">
							<li><label for="contextdescription">description: </label><span id="">${ term.context.description }</span></li> <%-- TODO-i18n --%>
						</c:if>
						<li><label for="contexturi">URI: </label><span id="contexturi">${ term.context.URI }</span></li> <%-- TODO-i18n --%>
					</ul>
					
					<h2>Related Items:</h2> <%-- TODO-i18n --%>
					<c:if test="${ term.context.type eq 'TAXONOMY' and term.class.name ne 'com.kh.ov.entities.EntryEntity' }">			
						<c:if test="${ not empty term.parent }">
						<h4>Parent term:</h4>
							<ul>
							<c:choose>
								<c:when test="${ iswn }">
									<li><a href="/vocabularies/lookup?uri=${ term.parent.URI }">${ term.parent.label }</a></li>
								</c:when>
								<c:otherwise>
									<li><a href="${ term.parent.URI }">${ term.parent.label }</a></li>
								</c:otherwise>
							</c:choose>
							</ul>
						</c:if>
			
						<c:if test="${ not empty term.subEntries }">
						<h4>Children terms:</h4>
						<ul>
						<c:forEach items="${ term.subEntries }" var="relatedterm">
							<c:choose>
								<c:when test="${ iswn }">
									<li><a href="/vocabularies/lookup?uri=${ relatedterm.URI }">${ relatedterm.label }</a></li>
								</c:when>
								<c:otherwise>
									<li><a href="${ relatedterm.URI }">${ relatedterm.label }</a></li>
								</c:otherwise>
							</c:choose>
						</c:forEach>
						</ul>
						</c:if>
					</c:if>
					
					<c:if test="${ term.context.type eq 'THESAURUS'  and term.class.name ne 'com.kh.ov.entities.EntryEntity' }">			
						<c:if test="${ not empty term.synonyms }">
						<h4>Synonyms:</h4>
						<ul>
						<c:forEach items="${ term.synonyms }" var="relatedterm">
							<c:choose>
								<c:when test="${ iswn }">
									<li><a href="/vocabularies/lookup?uri=${ relatedterm.URI }">${ relatedterm.label }</a></li>
								</c:when>
								<c:otherwise>
									<li><a href="${ relatedterm.URI }">${ relatedterm.label }</a></li>
								</c:otherwise>
							</c:choose>
						</c:forEach>
						</ul>
						</c:if>
						
						<c:if test="${ not empty term.hypernyms }">
						<h4>Hypernyms:</h4>
						<ul>
						<c:forEach items="${ term.hypernyms }" var="relatedterm">
							<c:choose>
								<c:when test="${ iswn }">
									<li><a href="/vocabularies/lookup?uri=${ relatedterm.URI }">${ relatedterm.label }</a></li>
								</c:when>
								<c:otherwise>
									<li><a href="${ relatedterm.URI }">${ relatedterm.label }</a></li>
								</c:otherwise>
							</c:choose>
						</c:forEach>
						</ul>
						</c:if>
						
						<c:if test="${ not empty term.hyponyms }">
						<h4>Hyponyms:</h4>
						<ul>
						<c:forEach items="${ term.hyponyms }" var="relatedterm">
							<c:choose>
								<c:when test="${ iswn }">
									<li><a href="/vocabularies/lookup?uri=${ relatedterm.URI }">${ relatedterm.label }</a></li>
								</c:when>
								<c:otherwise>
									<li><a href="${ relatedterm.URI }">${ relatedterm.label }</a></li>
								</c:otherwise>
							</c:choose>
						</c:forEach>
						</ul>
						</c:if>
						
						<c:if test="${ not empty term.antonyms }">
						<h4>Antonyms:</h4>
						<ul>
						<c:forEach items="${ term.antonyms }" var="relatedterm">
							<c:choose>
								<c:when test="${ iswn }">
									<li><a href="/vocabularies/lookup?uri=${ relatedterm.URI }">${ relatedterm.label }</a></li>
								</c:when>
								<c:otherwise>
									<li><a href="${ relatedterm.URI }">${ relatedterm.label }</a></li>
								</c:otherwise>
							</c:choose>
						</c:forEach>
						</ul>
						</c:if>
					</c:if>
					
					<hr/>			
					 
					<c:forEach items="${ term.context.treeProperties }" var="treeprop">
						<h4><a href="${ treeprop }">${ treeprop }</a></h4>	
						<ul>
							<c:forEach items="${ ov:getRelatedEntries( term, treeprop ) }" var="relatedterm">
							<c:choose>
								<c:when test="${ iswn }">
									<li><a href="/vocabularies/lookup?uri=${ relatedterm.URI }">${ relatedterm.label }</a></li>
								</c:when>
								<c:otherwise>
									<li><a href="${ relatedterm.URI }">${ relatedterm.label }</a></li>
								</c:otherwise>
							</c:choose>
							</c:forEach>
						</ul>
					</c:forEach>
					
					
					<c:forEach items="${ term.context.additionalProperties }" var="addprop">
						<h3><a href="${ addprop }">${ addprop }</a></h3>	
						<ul>
							<c:forEach items="${ ov:getRelatedEntries( term, addprop ) }" var="relatedterm">
								<c:when test="${ iswn }">
									<li><a href="/vocabularies/lookup?uri=${ relatedterm.URI }">${ relatedterm.label }</a></li>
								</c:when>
								<c:otherwise>
									<li><a href="${ relatedterm.URI }">${ relatedterm.label }</a></li>
								</c:otherwise>
							</c:forEach>
						</ul>
					</c:forEach>
				</c:when>
				<c:otherwise>
					The best way to start browsing through the OpenVocabulary repository is to start with one of <a href="/vocabularies/" rel="self" title="Vocabularies">vocabularies</a>.
				</c:otherwise>
			</c:choose>
		
			<div class="clearer"></div>
			<div id="breadcrumbcontainer"><!-- Start the breadcrumb wrapper -->
				<ul><li><a href="/">Welcome</a>&nbsp;>&nbsp;</li><li><a href="#">Browse</a>&nbsp;>&nbsp;</li></ul>
			</div><!-- End breadcrumb -->
		</div><!-- End content -->
	</div><!-- End main content wrapper -->
	
	<div id="sidebarContainer"><!-- Start Sidebar wrapper -->
		<div class="top"></div>
		<div id="logo"><img src="/rw_common/images/ovlogo.png" width="181" height="130" alt="Site logo"/></div>
		<div id="sidebar"><!-- Start sidebar content -->
			<h1 class="sideHeader"></h1><!-- Sidebar header -->
			<span style="font:10px Monaco; "><form class="search" id="search_form" action="/vocabularies/search" method="get">
	<input type="search" id="proj-search" name="q" size="15" accesskey="f" autosave="at.search" results="5" placeholder="Search" value="" /><button type="submit">search</button>
	</form></span> <br /><!-- sidebar content you enter in the page inspector -->
			 <!-- sidebar content such as the blog archive links -->
		</div><!-- End sidebar content -->
		<div class="bottom"></div>
	</div><!-- End sidebar wrapper -->

<div class="clearer"></div>
<div id="footer"><!-- Start Footer -->
	<p>&copy; 2009 <a href="http://www.knowledgehives.com/">Knowledge Hives</a> |  <a href="#" id="rw_email_contact">Contact Us</a><script type="text/javascript">var _rwObsfuscatedHref0 = "mai";var _rwObsfuscatedHref1 = "lto";var _rwObsfuscatedHref2 = ":op";var _rwObsfuscatedHref3 = "env";var _rwObsfuscatedHref4 = "oca";var _rwObsfuscatedHref5 = "bul";var _rwObsfuscatedHref6 = "ary";var _rwObsfuscatedHref7 = "@kn";var _rwObsfuscatedHref8 = "owl";var _rwObsfuscatedHref9 = "edg";var _rwObsfuscatedHref10 = "ehi";var _rwObsfuscatedHref11 = "ves";var _rwObsfuscatedHref12 = ".co";var _rwObsfuscatedHref13 = "m";var _rwObsfuscatedHref = _rwObsfuscatedHref0+_rwObsfuscatedHref1+_rwObsfuscatedHref2+_rwObsfuscatedHref3+_rwObsfuscatedHref4+_rwObsfuscatedHref5+_rwObsfuscatedHref6+_rwObsfuscatedHref7+_rwObsfuscatedHref8+_rwObsfuscatedHref9+_rwObsfuscatedHref10+_rwObsfuscatedHref11+_rwObsfuscatedHref12+_rwObsfuscatedHref13; document.getElementById('rw_email_contact').href = _rwObsfuscatedHref;</script></p>
</div><!-- End Footer -->
<div class="bottom">&nbsp;</div>
</div><!-- End container -->
<!-- Start Google Analytics -->
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-5357587-3");
pageTracker._trackPageview();
} catch(err) {}</script><!-- End Google Analytics --></body>
</html>